import Foundation
import CryptoKit

/// Verifies GDC-format license serials — a Swift port of
/// gdc-license-system's `license_core.py` (`validate_serial`), kept
/// byte-for-byte compatible so codes generated by the existing Python
/// tooling (`generate_serial.py`) work here unchanged, and so future GDC
/// products can keep sharing one signing key + one set of admin tools.
///
/// Format: Base32(dash-grouped) of
/// `[2-byte big-endian payload length][JSON payload][64-byte Ed25519 signature]`,
/// payload = `{"p": <8-char product short code>, "e": <expiry unix
/// seconds, 0 = never>, "c": <optional customer name>}`.
///
/// Verification only ever uses the PUBLIC key — the private key that
/// signs new codes stays on Cristi's machine in `gdc-license-system/`,
/// never in this app.
enum LicenseCore {
    struct Payload {
        let customer: String
        let expiresAt: Int64 // unix seconds, 0 = never expires
    }

    enum ValidationError: Error {
        case malformedCode
        case badSignature
        case wrongProduct
        case expired(Int64)
    }

    /// Base64 of the Ed25519 PUBLIC key from gdc-license-system's
    /// keygen.py (`public_key.txt`). Safe to embed: with asymmetric
    /// crypto, only the never-distributed private key can forge a
    /// signature this validates.
    private static let publicKeyBase64 = "I1h23MNMRbOhc0ObKJrfa3oFHKA9w+SzbNrroAIy8hs="

    /// Same derivation as `_product_short_code` in license_core.py: a
    /// short, collision-free stand-in for the full product id, so two
    /// similarly-named products (e.g. "cursorpro" and "cursorpro-beta")
    /// never get confused with a naive string-prefix comparison.
    static func productShortCode(for productID: String) -> String {
        let digest = SHA256.hash(data: Data(productID.utf8))
        return base32Encode(Data(digest.prefix(5)))
    }

    /// Validates a serial the user typed/pasted against `expectedProductID`.
    static func validate(serial: String, expectedProductID: String) -> Result<Payload, ValidationError> {
        guard let packed = base32Decode(serial), packed.count >= 2 else {
            return .failure(.malformedCode)
        }

        let payloadLen = Int(packed[packed.startIndex]) << 8 | Int(packed[packed.startIndex + 1])
        let headerEnd = packed.startIndex + 2
        guard packed.count >= 2 + payloadLen + 64 else { return .failure(.malformedCode) }

        let payloadBytes = packed.subdata(in: headerEnd..<(headerEnd + payloadLen))
        let signature = packed.subdata(in: (headerEnd + payloadLen)..<(headerEnd + payloadLen + 64))

        guard let publicKeyData = Data(base64Encoded: publicKeyBase64),
              let publicKey = try? Curve25519.Signing.PublicKey(rawRepresentation: publicKeyData) else {
            return .failure(.malformedCode)
        }
        guard publicKey.isValidSignature(signature, for: payloadBytes) else {
            return .failure(.badSignature)
        }

        guard let json = try? JSONSerialization.jsonObject(with: payloadBytes) as? [String: Any],
              let storedShortCode = json["p"] as? String else {
            return .failure(.malformedCode)
        }
        let expiresAt = (json["e"] as? NSNumber)?.int64Value ?? 0
        let customer = json["c"] as? String ?? ""

        guard storedShortCode == productShortCode(for: expectedProductID) else {
            return .failure(.wrongProduct)
        }

        if expiresAt != 0 && expiresAt < Int64(Date().timeIntervalSince1970) {
            return .failure(.expired(expiresAt))
        }
        return .success(Payload(customer: customer, expiresAt: expiresAt))
    }

    // MARK: - Base32 (RFC 4648, matching Python's base64.b32encode/decode)

    private static let base32Alphabet = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ234567")

    private static func base32Encode(_ data: Data) -> String {
        var bits = 0, value = 0
        var output = ""
        for byte in data {
            value = (value << 8) | Int(byte)
            bits += 8
            while bits >= 5 {
                output.append(base32Alphabet[(value >> (bits - 5)) & 0x1F])
                bits -= 5
            }
        }
        if bits > 0 {
            output.append(base32Alphabet[(value << (5 - bits)) & 0x1F])
        }
        return output
    }

    private static func base32Decode(_ string: String) -> Data? {
        let cleaned = string.uppercased()
            .replacingOccurrences(of: "-", with: "")
            .replacingOccurrences(of: " ", with: "")
            .replacingOccurrences(of: "=", with: "")
        var bits = 0, value = 0
        var output = [UInt8]()
        for char in cleaned {
            guard let index = base32Alphabet.firstIndex(of: char) else { return nil }
            value = (value << 5) | index
            bits += 5
            if bits >= 8 {
                output.append(UInt8((value >> (bits - 8)) & 0xFF))
                bits -= 8
            }
        }
        return Data(output)
    }
}
